# Homework 4

## Problem 1

What's your favorite movie? Search for it on IMDB. If you can't find your favorite movie there, pick your second favorite or third favorite. 

Once you've found your favorite movie on IMDB, find the "Full Cast and Crew" page (under the "Cast") section. Here's the [Full Cast and Crew page](https://www.imdb.com/title/tt0211915/fullcredits?ref_=tt_cl_sm#cast) for my favorite movie, *Amelie*. Yours should look similar to this one.  

We are going to use regular expressions to extract a list of all the actors in your favorite movie. 

### (A).

Load the HTML from the Full Cast and Crew page into a variable called `html`. You will need to import the `urllib` library; copy/paste the page's URL; retrieve the data, read the data, and decode the data. The code pattern required should be nearly identical to that used in Discussion Activity 10. 

### Your Solution

In [5]:
import urllib

url = "https://www.imdb.com/title/tt0211915/fullcredits?ref_=tt_cl_sm#cast"

# retrieve the data
filedata   = urllib.request.urlopen(url)

# read as bytes
bytes_text = filedata.read()

# decode bytes to string
html = bytes_text.decode("utf-8") 
print(html)












<!DOCTYPE html>
<html
    xmlns:og="http://ogp.me/ns#"
    xmlns:fb="http://www.facebook.com/2008/fbml">
    <head>
         
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="apple-itunes-app" content="app-id=342792525, app-argument=imdb:///title/tt0211915?src=mdot">



        <script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>

<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle", {wb: 1});
    }
</script>
  <script>(function(t){ (t.events = t.events || {})["csm_head_pre_title"] = new Date().getTime(); })(IMDbTimer);</script>
        <title>Amélie (2001) - Full Cast &amp; Crew - IMDb</title>
  <script>(function(t){ (t.events = t.events || {})["csm_head_post_title"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadTitle", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'functi

### (B). 

In order to extract the complete cast, we are going to be a little bit sneaky. A sneaky streak is often helpful when working with regular expressions. 

If you investigate the HTML (which you are welcome but not required to do), you will find that all the actors have a small image associated to their names. The "alt text" on this image (i.e. the text displayed when you hover over that image with a mouse) contains the actor's name. So, we can simply extract the alt text to get a list of the actors. 

The corresponding HTML element looks like this: 

```
<img height="44" width="32" alt="Audrey Tautou" title="Audrey Tautou" src="img.png" class="loadlate hidden " loadlate="img2.jpg" />
```
Write a pattern that matches this HTML element and captures the name of the actor in a group. You should be able to use your pattern with `re.findall` to construct a complete list of actors in the movie:

```python
import re
pattern = ?? # your solution here
re.findall(pattern, html)
```
```
['Audrey Tautou',
 'Mathieu Kassovitz',
 'Rufus',
 'Lorella Cravotta',
 'Serge Merlin',
 ...]
```

You should show your list output with your solution, and check it against the IMDB page to ensure that you've got everyone. You should also check whether your expression matches anything that ISN'T an actor, and adjust it if so. 

Feel free to grab some relevant chunks of HTML and paste them into [Pythex](https://pythex.org/) as you construct your expression. 

### Your Solution

In [ ]:
import re
pattern = ?? # your solution here
re.findall(pattern, html)

## Problem 2

Construct the following `numpy` arrays. For full credit, you should **not** use the code pattern `np.array(my_list)` in any of your answers, nor should you use `for`-loops or any other solution that involves creating or modifying the array one entry at a time. 

### (A). 

```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
```

#### Your Solution

In [ ]:
# run this block to import numpy
import numpy as np

### (B). 

```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

#### Your Solution

### (C). 

```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

#### Your Solution

### (D). 

```
array([ 1,  1,  1,  1,  1, 10, 10, 10, 10, 10])
```

#### Your Solution

### (E).
```
array([[30,  1,  2, 30,  4],
       [ 5, 30,  7,  8, 30]])
```

#### Your Solution

### (F).

```
array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
```
#### Your Solution

### (G). 

```
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])
```
#### Your Solution

## Problem 3

Consider the following array:

```python
A = np.arange(12).reshape(4, 3)
A
```
```
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```

Construct the specified arrays by indexing `A`. For example, if asked for `array([0, 1, 2])`, a correct answer would be `A[0,:]`. Each of the parts below may be performed in a single line. 

### (A). 

```
array([6, 7, 8])
```

In [ ]:
# run this block to initialize A
A = np.arange(12).reshape(4, 3)
A

#### Your Solution

### (B). 

```
array([5, 8])
```

#### Your Solution

### (C). 

```
array([ 6,  7,  8,  9, 10, 11])
```

#### Your Solution

### (D). 

```
array([ 0,  2,  4,  6,  8, 10])
```

#### Your Solution

### (E). 

```
array([ 0,  1,  2,  3,  4,  5, 11])
```

#### Your Solution

### (F). 

```
array([ 4, 11])
```

#### Your Solution

## Problem 4

In this problem, we will use `numpy` array indexing to repair an image that has been artificially separated into multiple pieces. The following code will retrieve two images, one of which has been cutout from the other. Your job is to piece them back together again. 

You've already seen `urllib.request.urlopen()` to retrieve online data. We'll play with `mpimg.imread()` a bit more in the future. The short story is that it produces a representation of an image as a `numpy` array of `RGB` values; see below. You'll see `imshow()` a lot more in about a week. 

In [ ]:
import matplotlib.image as mpimg 
from matplotlib import pyplot as plt
import urllib

f    = urllib.request.urlopen("https://philchodrow.github.io/PIC16A/homework/main.jpg")
main = mpimg.imread(f, format = "jpg").copy()

f     = urllib.request.urlopen("https://philchodrow.github.io/PIC16A/homework/cutout.jpg")
cutout= mpimg.imread(f, format = "jpg").copy()

fig, ax = plt.subplots(1, 2)
ax[0].imshow(main)
ax[1].imshow(cutout)

The images are stored as two `np.array`s `main` and `cutout`. Inspect each one. You'll observe that each is a 3-dimensional `np.array` of shape `(height, width, 3)`. The `3` in this case indicates that the color of each pixel is encoded as an RGB (Red-Blue-Green) value. Each pixel has one RGB value, each of which has three elements. 

Use array indexing to fix the image, resulting in an array `fixed` that contains all the required RGB values. This can be done just a few lines of carefully-crafted `numpy`. Once you're done, visualize the result by running the indicated code block. 

**The black region in `main` starts at row 0, and column 50**. You can learn more about its shape by inspecting the shape of `cutout`. 

In [ ]:
# your solution


In [ ]:
# run this block to check your solution
plt.imshow(main)

## Problem 5

### (A).

Read [these notes](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) from the Python Data Science Handbook on *array broadcasting*. Broadcasting refers to the automatic expansion of one or more arrays to make a computation "make sense." Here's a simple example: 

```python
a = np.array([0, 1, 2])
b = np.ones((3, 3))
a.shape, b.shape
```
```
((3,), (3, 3))
```
```python
a+b
```
```
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])
```

What has happened here is that the first array `a` has been "broadcast" from a 1d array into a 2d array of size 3x3 in order to match the dimensions of `b`. The broadcast version of `a` looks like this: 

```
array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])
```

Consult the notes above for many more examples of broadcasting. Pay special attention to the discussion of the [rules of broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html#Rules-of-Broadcasting). 

### (B). 

Review, if needed, the `unittest` module for constructing automated unit tests in Python. You may wish to refer to the [required reading](https://docs.python.org/3/library/unittest.html) from that week, the [lecture notes](https://nbviewer.jupyter.org/github/PhilChodrow/PIC16A/blob/master/content/IO_and_modules/modules/unit_testing.ipynb), or the recorded [lecture video](https://www.youtube.com/watch?v=TwOmk9oSaR8&feature=youtu.be). 

### (C). 

Implement an automated test class called `TestBroadcastingRules` which tests the three rules of array broadcasting. 

> **Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

To test this rule, write a method `test_rule_1()` that constructs the arrays:

```
a = np.ones(3)
b = np.arange(3).reshape(1, 3) 
c = a + b
```

Then, within the method, check (a) that the `shape` of `c` has the value you would expect according to Rule 1 and (b) that the final entry of `c` has the value that you would expect. **Note:** you should use `assertEqual()` twice within this method. 

In a docstring to this method, explain how this works. In particular, explain which of `a` or `b` is broadcasted, and what its new shape is according to Rule 1. You should also explain the value of the final entry of `c`. 

> **Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

To test this rule, write a method `test_rule_2()` that constructs the following two arrays: 

```
a = np.ones((1, 3))
b = np.arange(9).reshape(3, 3)
c = a + b
```

Then, within the method, check (a) that the `shape` of `c` has the value you would expect according to Rule 2 and (b) that the entry `c[1,2]` has the value that you would expect.  You should again use `assertEqual()` twice within this method. 

In a docstring to this method, explain how this works. In particular, explain which of `a` or `b` is broadcasted, and what its new shape is according to Rule 2. You should also explain the value of the entry `c[1,2]`. 

> **Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

To test this rule, write a method `test_rule_3` that constructs the arrays 

```
a = np.ones((2, 3))
b = np.ones((3, 3))
```

It should then attempt to construct `c = a + b`. The test should *pass* if the Rule 3 error is raised, and fail otherwise. You will need to figure out what kind of error is raised by Rule 3 (is it a `TypeError`? `ValueError`? `KeyError`?). You will also need to handle the error using the `assertRaises()` method as demonstrated in the readings. 

In a docstring to this method, explain why an error is raised according to Rule 3. 

You should be able to perform the unit tests like this: 

```
tester = TestBroadcastingRules()
tester.test_rule_1()
tester.test_rule_2()
tester.test_rule_3()
```

Your tests have passed if no output is printed when you run this code. 

### Your Solution

In [ ]:
# write your tester class here


In [ ]:
# run your tests
# your tests have passed if no output or errors are shown. 

tester = TestBroadcastingRules()
tester.test_rule_1()
tester.test_rule_2()
tester.test_rule_3()